ServerEvents.recipes(event => {
    //洗矿机
    event.replaceInput(
        {id:'industrialforegoing:washing_factory'},
        'industrialforegoing:plastic',
        'gtceu:epoxy_plate'
    )
    event.replaceInput(
        {id:'industrialforegoing:washing_factory'},
        'gtceu:diamond_gear',
        'gtceu:titanium_gear'
    )
    //流体筛分
    event.replaceInput(
        {id:'industrialforegoing:fluid_sieving_machine'},
        'industrialforegoing:plastic',
        'gtceu:epoxy_plate'
    )
    event.replaceInput(
        {id:'industrialforegoing:fluid_sieving_machine'},
        'thermal:gold_gear',
        'gtceu:titanium_gear'
    )
    //发酵机
    event.replaceInput(
        {id:'industrialforegoing:fermentation_station'},
        'industrialforegoing:plastic',
        'gtceu:epoxy_plate'
    )
    event.replaceInput(
        {id:'industrialforegoing:fermentation_station'},
        'industrialforegoing:machine_frame_simple',
        'industrialforegoing:machine_frame_advanced'
    )
    event.replaceInput(
        {id:'industrialforegoing:fermentation_station'},
        'thermal:gold_gear',
        'gtceu:titanium_gear'
    )
})