ServerEvents.recipes(event =>{
    const GTR = event.recipes.gtceu
    //主世界LV
    //4x
    GTR.mining_drone("miningdrone:overworld_mining_lv/4")
        .notConsumable(
            '4x miningdrone:mining_drone_lv'
        )
        .inputFluids(
            Fluid.of('gtceu:diesel', 4000)
        )
        .chancedOutput(Item.of('gtceu:raw_cassiterite', 4), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_goethite', 4), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_yellow_limonite', 4), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_hematite', 4), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_malachite', 4), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_chalcopyrite', 4), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_pyrite', 4), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_cassiterite_sand', 4), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_garnet_sand', 4), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_asbestos', 4), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_magnetite', 4), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_vanadium_magnetite', 4), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_basaltic_mineral_sand', 4), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_granitic_mineral_sand', 4), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_fullers_earth', 4), 5000, 0,)
        .chancedOutput(Item.of('gtceu:raw_gypsum', 4), 4000, 0,)
        .chancedOutput(Item.of('gtceu:raw_diatomite', 4), 4000, 0,)
        .chancedOutput(Item.of('minecraft:raw_gold', 4), 3000, 0)
        .EUt(32)
        .duration(200)
        .circuit(4)
        .dimension("minecraft:overworld")
    //8x
    GTR.mining_drone('miningdrone:overworld_mining_lv/8')
        .notConsumable(
            '8x miningdrone:mining_drone_lv'
        )
        .inputFluids(
            Fluid.of('gtceu:diesel', 8000)
        )
        .chancedOutput(Item.of('gtceu:raw_cassiterite', 8), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_goethite', 8), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_yellow_limonite', 8), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_hematite', 8), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_malachite', 8), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_chalcopyrite', 8), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_pyrite', 8), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_cassiterite_sand', 8), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_garnet_sand', 8), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_asbestos', 8), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_magnetite', 8), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_vanadium_magnetite', 8), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_basaltic_mineral_sand', 8), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_granitic_mineral_sand', 8), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_fullers_earth', 8), 5000, 0,)
        .chancedOutput(Item.of('gtceu:raw_gypsum', 8), 4000, 0,)
        .chancedOutput(Item.of('gtceu:raw_diatomite', 8), 4000, 0,)
        .chancedOutput(Item.of('minecraft:raw_gold', 8), 3000, 0)
        .EUt(32)
        .duration(200)
        .circuit(8)
        .dimension("minecraft:overworld")
    //16x
    GTR.mining_drone('miningdrone:overworld_mining_lv/16')
        .notConsumable(
            '16x miningdrone:mining_drone_lv'
        )
        .inputFluids(
            Fluid.of('gtceu:diesel', 16000)
        )
        .chancedOutput(Item.of('gtceu:raw_cassiterite', 16), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_goethite', 16), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_yellow_limonite', 16), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_hematite', 16), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_malachite', 16), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_chalcopyrite', 16), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_pyrite', 16), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_cassiterite_sand', 16), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_garnet_sand', 16), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_asbestos', 16), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_magnetite', 16), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_vanadium_magnetite', 16), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_basaltic_mineral_sand', 16), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_granitic_mineral_sand', 16), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_fullers_earth', 16), 5000, 0,)
        .chancedOutput(Item.of('gtceu:raw_gypsum', 16), 4000, 0,)
        .chancedOutput(Item.of('gtceu:raw_diatomite', 16), 4000, 0,)
        .chancedOutput(Item.of('minecraft:raw_gold', 16), 3000, 0)
        .EUt(32)
        .duration(200)
        .circuit(16)
        .dimension("minecraft:overworld")
    //32
    GTR.mining_drone('miningdrone:overworld_mining_lv/32')
        .notConsumable(
            '32x miningdrone:mining_drone_lv'
        )
        .inputFluids(
            Fluid.of('gtceu:diesel', 32000)
        )
        .chancedOutput(Item.of('gtceu:raw_cassiterite', 32), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_goethite', 32), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_yellow_limonite', 32), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_hematite', 32), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_malachite', 32), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_chalcopyrite', 32), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_pyrite', 32), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_cassiterite_sand', 32), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_garnet_sand', 32), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_asbestos', 32), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_magnetite', 32), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_vanadium_magnetite', 32), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_basaltic_mineral_sand', 32), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_granitic_mineral_sand', 32), 6000, 0,)
        .chancedOutput(Item.of('gtceu:raw_fullers_earth', 32), 5000, 0,)
        .chancedOutput(Item.of('gtceu:raw_gypsum', 32), 4000, 0,)
        .chancedOutput(Item.of('gtceu:raw_diatomite', 32), 4000, 0,)
        .chancedOutput(Item.of('minecraft:raw_gold', 32), 3000, 0)
        .EUt(32)
        .duration(200)
        .circuit(32)
        .dimension("minecraft:overworld")
})