ServerEvents.recipes(event => {
    //铝土
    event.remove({id:'immersiveengineering:smelting/ingot_aluminum'})
    event.remove({id:'immersiveengineering:smelting/ingot_aluminum2'})
    event.remove({id:'immersiveengineering:smelting/ingot_aluminum_from_blasting'})
    event.remove({id:'immersiveengineering:smelting/ingot_aluminum_from_blasting2'})
    event.remove({id:'enderio:smelting/immersiveengineering/smelting/ingot_aluminum'})
    event.remove({id:'enderio:smelting/immersiveengineering/smelting/ingot_aluminum2'})
    event.remove({id:'thermal:compat/immersiveengineering/pulverizer_ie_aluminum_ore'})
    event.remove({id:'thermal:compat/immersiveengineering/smelter_ie_aluminum_ore'})
    //格雷硬币
    event.remove({id:'gtceu:forming_press/credit_cupronickel'})
    //时间之瓶
    event.remove({output:'tiab:time_in_a_bottle'})
    //铱
    event.remove({mod:'alltheores', input:'gtceu:iridium_dust', output:'gtceu:iridium_ingot'})
    //拆解台
    event.remove({id:'twilightforest:uncrafting_table'})
    //硅岩
    event.remove({id:'sgjourney:naquadah_alloy'})
    //删除无尽添加的创造物品配方
    event.remove({id:'avaritia:mek_creative_fluid_tank'})//mek储罐
    event.remove({id:'avaritia:mek_creative_chemical_tank'})//mek化学品储罐
    event.remove({id:'avaritia:mek_creative_energy_cube'})//mek能量立方
    event.remove({id:'avaritia:mek_creative_bin'})//mek箱柜
    event.remove({id:'avaritia:botania_creative_pool'})//永恒魔力池
    event.remove({id:'avaritia:botania_mana_tablet'})//魔力石板
    event.remove({id:'avaritia:eio_creative_power'})//eio创造能源
    event.remove({id:'avaritia:ae2_creative_energy_cell'})//ae2创造能源元件
    //无尽装备
    event.remove({id:'avaritia:infinity_helmet'})
    event.remove({id:'avaritia:infinity_chestplate'})
    event.remove({id:'avaritia:infinity_pants'})
    event.remove({id:'avaritia:infinity_boots'})
    //区块加载
    event.replaceInput(
        {id:"mekanism:dimensional_stabilizer"},
        'minecraft:diamond_block','mekanism:upgrade_anchor'
    )
    event.replaceInput(
        {id:"mekanism:upgrade/anchor"},
        '#forge:dusts/diamond','create_power_loader:brass_chunk_loader'
    )
})